In [1]:
import jax as J
import jax.numpy as jnp

In [5]:
x = jnp.arange(5)
x

DeviceArray([0, 1, 2, 3, 4], dtype=int32)

In [3]:
w = jnp.array([2., 3., 4.])
w

DeviceArray([2., 3., 4.], dtype=float32)

In [12]:
def convolve(x, w):
  output = []
  for i in range(1, len(x)-1):
    o = jnp.dot(x[i-1:i+2], w)
    output.append(o)
  return jnp.array(output)

convolve(x, w)

DeviceArray([11., 20., 29.], dtype=float32)

In [9]:
xs = jnp.stack([x, x])
ws = jnp.stack([w, w])

In [19]:
auto_vec_convolve = J.vmap(convolve, in_axes=1, out_axes=1)

# transpose!
%time result = auto_vec_convolve(xs.T, ws.T)

result

Wall time: 9 ms


DeviceArray([[11., 11.],
             [20., 20.],
             [29., 29.]], dtype=float32)

In [22]:
# with jit
j_convolve = J.jit(auto_vec_convolve)
%time j_convolve(xs.T, ws.T)

Wall time: 38 ms


DeviceArray([[11., 11.],
             [20., 20.],
             [29., 29.]], dtype=float32)